# Generated by Django 4.2 on 2024-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mergeMultipleExcel', '0002_uploadedfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
