# Generated by Django 4.2 on 2024-06-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mergeMultipleExcel', '0003_uploadedfile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='timestamp',
        ),
    ]
