# Generated by Django 4.2 on 2024-06-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mergeMultipleExcel', '0005_remove_uploadedfile_name_uploadedfile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='expiration_date',
        ),
    ]
